@ECHO OFF
REM generate C header for Git revision

REM current directoryに移動(src_user/Script/Git)
cd /d %~dp0

REM src_userに移動
cd ..\..

for /f "usebackq" %%a in (`"git log --pretty=format:%%H -1"`) do set git_rev_user=%%a
for /f "usebackq" %%a in (`"git log --pretty=format:%%h -1"`) do set git_rev_user_short=%%a

REM cd ..\..\src_core

REM generate header
if exist ..\Library\git_revision.h del ..\Library\git_revision.h

REM MEMO: このヒアドキュメントもどきの書き方はwineのcmd.exe(Windows 6.1.7601)だと動かない？
(
echo.#ifndef C2A_USER_GIT_REVISION_H_
echo.#define C2A_USER_GIT_REVISION_H_
echo.
echo./* This file is generated by src_user/Script/Git/revision.bat */
echo.
call ..\src_core\Script\Git\revision.bat
echo.#define GIT_REVISION_C2A_USER "$%git_rev_user%"
echo.#define GIT_REVISION_C2A_USER_SHORT 0x$%git_rev_user_short%
echo.
echo.#endif // C2A_USER_GIT_REVISION_H_
) >> Library\git_revision.h
