#!/bin/bash
# generate C header for Git revision

cd $(dirname $0)    # src/src_user/Script/Git
cd ../../           # src/src_user

# get core revision
git_revs_core=$(../src_core/Script/Git/revision.sh)

git_rev_user=$(git log --pretty=format:%H -1)
git_rev_user_short=$(git log --pretty=format:%h -1)

tee Settings/git_revision_config.h << EOS
#ifndef C2A_USER_GIT_REVISION_H_
#define C2A_USER_GIT_REVISION_H_

/* This file is generated by src_user/Script/Git/revision.sh */
#define C2A_GIT_REVISION_GENERATED

${git_revs_core}
#define GIT_REVISION_C2A_USER "${git_rev_user}"
#define GIT_REVISION_C2A_USER_SHORT 0x${git_rev_user_short}

#endif // C2A_USER_GIT_REVISION_H_
EOS
