/**
 * @file
 * @brief Telemetry Manager のパラメタのオーバーライド用ヘッダー
 */
#ifndef TELEMETRY_MANAGER_PARAMS_H_
#define TELEMETRY_MANAGER_PARAMS_H_

#undef TLM_MGR_BC_ROLE_AT_BC_0
#undef TLM_MGR_BC_ROLE_AT_BC_1
#undef TLM_MGR_BC_ROLE_AT_BC_2
#undef TLM_MGR_BC_ROLE_AT_BC_3
#undef TLM_MGR_BC_ROLE_AT_BC_4
#undef TLM_MGR_BC_ROLE_AT_BC_5
#undef TLM_MGR_BC_ROLE_AT_BC_6
#undef TLM_MGR_BC_ROLE_AT_BC_7
#undef TLM_MGR_BC_ROLE_AT_BC_8
#undef TLM_MGR_BC_ROLE_AT_BC_9

#define TLM_MGR_BC_ROLE_AT_BC_0   (TLM_MGR_BC_ROLE_HK_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_1   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_2   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_3   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_4   (TLM_MGR_BC_ROLE_LOW_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_5   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_6   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_7   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_8   (TLM_MGR_BC_ROLE_HIGH_FREQ_TLM)
#define TLM_MGR_BC_ROLE_AT_BC_9   (TLM_MGR_BC_ROLE_LOW_FREQ_TLM)

#endif
