/**
 * @file
 * @brief  コマンド定義
 * @note   このコードは自動生成されています！
 */
#ifndef AOBC_COMMAND_DEFINITIONS_H_
#define AOBC_COMMAND_DEFINITIONS_H_

typedef enum
{
  AOBC_Cmd_CODE_NOP = 0x0000,
  AOBC_Cmd_CODE_TMGR_SET_TIME = 0x0001,
  AOBC_Cmd_CODE_TMGR_UPDATE_UNIXTIME = 0x0002,
  AOBC_Cmd_CODE_TMGR_SET_UTL_UNIXTIME_EPOCH = 0x0003,
  AOBC_Cmd_CODE_TMGR_SET_CYCLE_CORRECTION = 0x0004,
  AOBC_Cmd_CODE_TMGR_RESET_CYCLE_CORRECTION = 0x0005,
  AOBC_Cmd_CODE_TMGR_CLEAR_UNIXTIME_INFO = 0x0006,
  AOBC_Cmd_CODE_AM_REGISTER_APP = 0x0007,
  AOBC_Cmd_CODE_AM_INITIALIZE_APP = 0x0008,
  AOBC_Cmd_CODE_AM_EXECUTE_APP = 0x0009,
  AOBC_Cmd_CODE_AM_SET_PAGE_FOR_TLM = 0x000A,
  AOBC_Cmd_CODE_AM_CLEAR_APP_INFO = 0x000B,
  AOBC_Cmd_CODE_MM_SET_MODE_LIST = 0x000C,
  AOBC_Cmd_CODE_MM_SET_TRANSITION_TABLE = 0x000D,
  AOBC_Cmd_CODE_MM_START_TRANSITION = 0x000E,
  AOBC_Cmd_CODE_MM_FINISH_TRANSITION = 0x000F,
  AOBC_Cmd_CODE_MM_UPDATE_TRANSITION_TABLE_FOR_TLM = 0x0010,
  AOBC_Cmd_CODE_TDSP_SET_TASK_LIST = 0x0011,
  AOBC_Cmd_CODE_TLCD_CLEAR_ALL_TIMELINE = 0x0012,
  AOBC_Cmd_CODE_TLCD_CLEAR_TIMELINE_AT = 0x0013,
  AOBC_Cmd_CODE_TLCD_SET_LINE_NO_FOR_TIMELINE_TLM = 0x0014,
  AOBC_Cmd_CODE_TLCD_DEPLOY_BLOCK = 0x0015,
  AOBC_Cmd_CODE_TLCD_SET_SOE_FLAG = 0x0016,
  AOBC_Cmd_CODE_TLCD_SET_LOUT_FLAG = 0x0017,
  AOBC_Cmd_CODE_TLCD_SET_PAGE_FOR_TLM = 0x0018,
  AOBC_Cmd_CODE_TLCD_CLEAR_ERR_LOG = 0x0019,
  AOBC_Cmd_CODE_GENERATE_TLM = 0x001A,

  AOBC_Cmd_CODE_MAX
} AOBC_CMD_CODE;

#endif
