name: build as C++ for S2E

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build_s2e_mockup:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        example:
          - minimum_user
          - 2nd_obc_user

    steps:
      - uses: actions/checkout@v4

      - name: setup
        shell: cmd
        run: ./setup.bat

      - name: cmake
        working-directory: ./Examples/${{ matrix.example }}/src/s2e_mockup
        run: |
          mkdir build
          cd build
          cmake --version
          cmake .. -A Win32

      - name: build
        working-directory: ./Examples/${{ matrix.example }}/src/s2e_mockup/build
        run: cmake --build .
