name: Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  minimum_user:
    name: minimum user
    uses: arkedge/workflows-c2a/.github/workflows/build.yml@v2.5.0
    with:
      c2a_dir: Examples/minimum_user
      c2a_custom_setup: |
        cd ../..
        pwd
        ls -l
        if [ $RUNNER_OS = 'Windows' ]; then
          cmd "/C setup.bat"
        else
          ./setup.sh
        fi
      cmake_generator_linux32: Ninja
      cmake_generator_win32: Ninja

  second_obc_user:
    name: 2nd obc user
    uses: arkedge/workflows-c2a/.github/workflows/build.yml@v2.5.0
    with:
      c2a_dir: Examples/2nd_obc_user
      c2a_custom_setup: |
        cd ../..
        pwd
        ls -l
        if [ $RUNNER_OS = 'Windows' ]; then
          cmd "/C setup.bat"
        else
          ./setup.sh
        fi
      cmake_generator_linux32: Ninja
      cmake_generator_win32: Ninja
