name: reviewdog / python format check

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  black_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install black formatter
        run: pip install black==23.1.0

      # - name: check python format with black
      #   uses: psf/black@stable

      - uses: reviewdog/action-black@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # reporter: github-pr-review    # TODO: いい感じになったら直す
          reporter: github-pr-check
          filter_mode: nofilter
          fail_on_error: true
          level: warning
